version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: notifications-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=adminpassword
      - POSTGRESQL_DATABASE=db_activityhub
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta de comunicação AMQP
      - "15672:15672" # UI de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
